<a href="https://colab.research.google.com/github/nabing259/numpy_practice_set/blob/main/NumPy_Practice_set_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy Practice Set - I

In [67]:
import numpy as np

###`Q-1` Create a null vector of size 10 but the fifth value which is 1.



In [5]:
vector = np.nan*np.empty(10)
vector[4] = 1
vector

array([nan, nan, nan, nan,  1., nan, nan, nan, nan, nan])

###`Q-2` Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.

In [ ]:
a = eval(input("Enter First Number: "))
b = eval(input("Enter Second Number: "))

array = np.random.randint(1, 100, size = (a,b))
print('The Array is:\n',array)
print('The Average of the Array is: ',np.average(array))

Enter First Number: 5
Enter Second Number: 4
The Array is:
 [[66  7 47 88]
 [58 56 50 68]
 [ 8 26 26 19]
 [77 37 68 70]
 [37 73 55 44]]
The Average of the Array is:  49.0


###`Q-3`Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.

Eg.-
```
[[1,1,1,1],
[1,0,0,1],
[1,0,0,1],
[1,1,1,1]]
```

In [ ]:
def create_array(a,b):
  array = np.ones((a,b), dtype=int)
  array[1:a-1, 1:b-1] = 0
  return array

a = eval(input("Enter First Number: "))
b = eval(input("Enter Second Number: "))
create_array(a,b)

Enter First Number: 10
Enter Second Number: 5


array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

###`Q-4` Create a vector of size 10 with values ranging from 0 to 1, both excluded.


In [ ]:
new_vector = np.random.uniform(0,1, size = 10)
new_vector

array([0.93416778, 0.09987605, 0.76207387, 0.95105372, 0.23526583,
       0.53837235, 0.54908402, 0.24272549, 0.3022125 , 0.78071879])

###`Q-5` Can you create a identity matrix of shape (4,4). If yes write code for it.

In [ ]:
identity_matrix = np.eye(4,4)
identity_matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

###`Q-6:` Create a 5x5 matrix with row values ranging from 0 to 4.

In [9]:
new_matrix = np.zeros((5,5))
new_matrix += np.arange(5)
new_matrix

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

###`Q-7:`  Consider a random integer (in range 1 to 100) vector with shape `(10,2)` representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vectros from the given point. Distance array should be interger type.

```
point = np.array([1,2])
```


In [30]:
vector1 = np.random.randint(1, 100, (10,2))
point = np.array([1,2])
np.sqrt(np.sum((vector1-point)**2, axis = 1)).astype(int)

array([115,  34, 122,  72,  84, 102,  65,  50, 108,  46])

###`Q-8:` Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [33]:
index_of_element = np.unravel_index(100, (6,7,8))
index_of_element

(np.int64(1), np.int64(5), np.int64(4))

### `Q-9:` Arrays

You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.



**Input Format:**

A single line of input containing space separated numbers.

**Output Format:**

Print the reverse NumPy array with type float.

**Example 1:**

Input:

```bash
1 2 3 4 -8 -10
```

Output:

```bash
[-10.  -8.   4.   3.   2.   1.]
```

In [37]:
arr = input().strip().split()
np.array(arr[::-1], dtype=float)

2 5 1 4


array([4., 1., 5., 2.])

### `Q-10:` Elements count

Count the number of elements of a numpy array.



**Example 1:**

Input:
```bash
np.array([])
```

Output:
```bash
elements_count :  0
```

**Example 2:**

Input:
```bash
np.array([1, 2])
```

Output:
```bash
elements_count :  2
```

In [42]:
arr = input().strip().split()
np_arr = np.array(arr, dtype=int)
np_arr.size

0

### `Q-12:` Vertical stack

Write a python function that accepts infinite number of numpy arrays and do the vertical stack to them. Then return that new array as result. The function only accepts the numpy array, otherwise raise error.



**Example 1:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]
```

Output:

```bash
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
```

**Example 2:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]

c= [[0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

Output:
```bash
[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

In [66]:
def vertical_stack(*args):
  for i in args:
    if type(i) != np.ndarray:
      raise TypeError (" Accept Numpy array only")
  return np.vstack(args)

arr1 = np.random.randint(1,10,(2,5))
arr2 = np.arange(10).reshape(2,5)
arr3 = np.random.random((2,5))

print(vertical_stack(arr1, arr2, arr3))

[[5.         5.         7.         6.         6.        ]
 [2.         8.         9.         1.         9.        ]
 [0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [0.52869005 0.18651551 0.40540137 0.24389643 0.89925606]
 [0.36030734 0.35371348 0.81607311 0.52671993 0.07642861]]


### `Q-13:` Dates

Create a python function named **date_array** that accepts two dates as string format and returns a numpy array of dates between those 2 dates. The function only accept 2 strings, otherwise raise error. The date format should be like this only: `2022-12-6`. The end date should be included and for simplicity, choose dates from a same year.



**Example 1:**

Input:
```bash
date_array(start = '2020-09-15', end = '2020-09-25')
```

Output:
```bash
['2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18',
 '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22',
 '2020-09-23', '2020-09-24', '2020-09-25']
```

**Example 2:**

Input:
```bash
date_array(start = '2022-12-01', end = '2022-12-06')
```

Output:
```bash
['2022-12-01', '2022-12-02', '2022-12-03', '2022-12-04', '2022-12-05', '2022-12-06']
```

**Example 3:**

Input:
```bash
date_array(start = '2020-11-25', end = '2020-11-30')
```

Output:
```bash
['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
 '2020-11-29', '2020-11-30']
```

In [ ]:
#Code here

###`Q-14:` Subtract the mean of each row from a matrix.

In [69]:
arr1 = np.random.randint(1,10,(4,5))
res = arr1-arr1.mean(axis=1, keepdims=True)
print(res)

[[ 0.2 -0.8  2.2  0.2 -1.8]
 [ 1.4 -0.6  0.4  2.4 -3.6]
 [-1.6  0.4  2.4 -2.6  1.4]
 [-1.6  0.4  1.4 -0.6  0.4]]


###`Q-15:` Swap column-1 of array with column-2 in the array.

In [74]:
arr1 = np.arange(9).reshape(3,3)
print('Actual Array:\n',arr1)

print('Swapped Array:\n', arr1[:, (0,2,1)])

Actual Array:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
Swapped Array:
 [[0 2 1]
 [3 5 4]
 [6 8 7]]


###`Q-16:` Replace odd elements in arrays with -1.

In [77]:
arr1 = np.arange(9).reshape(3,3)
arr1[arr1%2 != 0] = -1
arr1

array([[ 0, -1,  2],
       [-1,  4, -1],
       [ 6, -1,  8]])

###`Q-17:` Given two arrays of same shape make an array of max out of two arrays. (Numpy way)
```
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

Result-> [6 3 1 7 8]
```

In [81]:
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

a[b>a] = b[a<b]
print(a)

array([False, False, False,  True, False])

###`Q-18` Answer below asked questions on given array:
1. Fetch Every alternate column of the array
2. Normalise the given array

https://en.wikipedia.org/wiki/Normalization_(statistics)

There are different form of normalisation for this question use below formula.

$$\large X_{normalized} = \frac{X - X_{min}}{X_{max} - X_{min}}$$

```python
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
```


In [ ]:
# Given
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
arr1

array([[2939, 1694, 6680, 8865, 2684],
       [4066, 4573,  327, 6525,  851],
       [5997, 7481, 2315, 5863, 9615],
       [7821, 1225, 9138, 1114, 4885],
       [7715, 8046, 9105, 3935, 3182],
       [8842, 4836, 2705, 3751, 3800],
       [4132, 1400, 7844, 9471, 7526],
       [2749, 2624, 6900, 1576, 7515]])

In [ ]:
#Code here

###`Q-19:` Write a function which will accept 2 arguments.
First: A 1D numpy array arr

Second: An integer n {Please make sure n<=len(arr)}

Output: The output should be the nth largest item out of the array
```
# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40
```

In [83]:
def nth_largest(arr, n):
  if n>len(arr):
    raise IndexError ("n should be less than array length")
  arr.sort()
  return arr[-n]

arr=(12,34,40,7,1,0)
n=3
print(nth_largest(np.array(arr), n))

12


###`Q-20:` Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
```
# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```

In [84]:
a = np.array([1,2,3])

np.hstack([np.repeat(a,3), np.tile(a,3)])

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])